version: "3.5"

services:
    conan-training:
        container_name: conan-training
        build:
            dockerfile: Dockerfile
            context: ./conan-training
            args:
                CONAN_VERSION: ${CONAN_VERSION}
        networks:
            - conan-training
        command: tail -f /dev/null

    jfrog-artifactory-training:
        container_name: jfrog-artifactory-training
        build:
            dockerfile: Dockerfile
            context: ./artifactory-training
            args:
                ARTIFACTORY_VERSION: ${ARTIFACTORY_VERSION}
        networks:
            - conan-training
        ports:
            - "8082:8082"
        restart: always

networks:
    conan-training:
