stages:
  - test
  - name: deploy
    if: tag IS present

language: python

install:
  - pip install coverage
script:
  # run tests and report coverage
  - coverage run tests/run_tests.py
  - coverage report -m --omit=tests/run_tests.py

jobs:
  include:
    - stage: test
      python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - stage: deploy
      install:
      script:
        - "PACKAGE_VERSION=$(cat patch_ng.py | grep __version__ | head -1 | awk -F= '{ print $2 }' | sed 's/[ \",]//g')"
        - echo "Deploying library version '$PACKAGE_VERSION'"
        - echo "Tagged in repo as '$TRAVIS_TAG'"
        - |
          if [ "$PACKAGE_VERSION" != "$TRAVIS_TAG" ]; then
            echo "Library version and tag name mismatch!"
            travis_terminate 1
          fi
          
      deploy:
        provider: pypi
        user: "__token__"
        password:
          secure: "xQjEWfYtAHiFDMVxn7WeodCX3OiboVrJnaLQTk9EiZEHXmLViA0BknyuNR5MVYwv+mIeWKU70scPgzhMw7Dn6A6o/NVFdJIXmUkxttWMTLia0uPyhfFDSefFH2dRECU2vo4fIgWxBzDKGsNYtHDHjvsIRTl9PsWwBKYaKNl+w6einTUNwTyQvMdpQjQ/VV3dQnMQqc86LkDXpAhNVHFe+cbA+phk8WGrsamlyd+vEJ7xgNSotNp0405IPbXLSxC7wo5qAfKgeIjXwHN6OV1IcbKiUGD9iw0QUKme3Gqmr4kNC+9eQQ+SrOv1Crpmsa8/q7F3ECvJ/NVAzzJ7/ZiMdkhfumzn8J9tvOdjQ6lx78it0xToL2h5tmN3gClyawrA/0VUzLDih7UjFTkolGVXAoZzqiBJdb5NLS06JlGp01c9cxotqeAdylHRptx5ovrYZsf7GHjXYvxg/ry9SjyQN0hb3l62WQCilqf4DX2iEgDHQX6ushvpHmNQseQCti4gvsMj8CQkhhK2PASB6cHsQ1GZXFdQ0QtQ1nw6mI461iiF0xDNfRQuRFSf8tmnhdgqC9s7yfI+vD1uN3mVnIP0j+B6G0DTvjOcI+vasWcbQSrwRdBFl9e/Gjlu26jEaxmPWDCH/FvLmDFRlVSOibGBL4MZPvUJGMMNlMm+N2pBta0="
        on:
          tags: true
