build: false

environment:

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          PYTHON: "C:\\Python27"
          PYTHON_ARCH: "32"
          PYTHON_VERSION: "2.7.x"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          PYTHON: "C:\\Python27-x64"
          PYTHON_ARCH: "64"
          PYTHON_VERSION: "2.7.x"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          PYTHON: "C:\\Python38"
          PYTHON_ARCH: "32"
          PYTHON_VERSION: "3.8.x"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          PYTHON: "C:\\Python38-x64"
          PYTHON_ARCH: "64"
          PYTHON_VERSION: "3.8.x"

test_script:
- python tests/run_tests.py